# Generated by Django 4.2.3 on 2023-08-03 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
